import type { Metadata } from 'next';
import './globals.css';
import Header from 'src/components/section/header';
import {AuthProvider} from "src/context/auth";

export const metadata: Metadata = {
    title: 'Sugimoto Challenge',
    description: 'Generated by mhmk',
};

function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <AuthProvider>
                    <Header />
                    {children}
                </AuthProvider>
            </body>
        </html>
    );
}

export default RootLayout;
